[package]
name = "proxmox-uuid"
description = "bindings for libuuid with optional serde support"
version = "1.1.0"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true, optional = true }

[features]
default = []

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_arch="wasm32")'.dependencies]
js-sys = "0.3.55"
