[package]
name = "proxmox-router"
description = "proxmox API Router and CLI utilities"
version = "3.1.0"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[test]]
name = "docs"
path = "tests/docs.rs"
test = true
required-features = [ "cli" ]

[dependencies]
anyhow.workspace = true
env_logger = { workspace = true, optional = true }
futures.workspace = true
http = { workspace = true, optional = true }
hyper = { workspace = true, features = [ "full" ], optional = true }
nix.workspace = true
percent-encoding.workspace = true
serde = { workspace = true, features = [ "derive" ] }
serde_json.workspace = true
serde_plain.workspace = true
unicode-width ="0.1.8"

# cli:
rustyline = { version = "9", optional = true }
libc = { workspace = true, optional = true }

proxmox-http-error.workspace = true
proxmox-schema.workspace = true
proxmox-async.workspace = true

[dev-dependencies]
tokio.workspace = true
tokio-stream.workspace = true

[features]
default = [ "cli", "server" ]
cli = [ "stream", "dep:env_logger", "dep:libc", "dep:rustyline" ]
server = [ "dep:http", "dep:hyper" ]
test-harness = [ "proxmox-schema/test-harness" ]
stream = [ "dep:hyper" ]
